name: Build - Test
on:
  pull_request:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: zendesk/checkout@v4

      - name: Check that package-lock.json is valid JSON
        run: jq empty package-lock.json

      - run: "npm ci && npm run build && npm run package"
