name: Build
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: zendesk/checkout@v2
      - run: "npm install && npm run build && npm run package"
